{% set name = "types-psutil" %}
{% set version = "7.1.3.20251130" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7f42e7a7845a93397e430b48a8074a35410d7a436695fd3375ec9b687d8d95f8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - setuptools
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  files:
    - stubtest_allowlist.txt
    - stubtest_allowlist_linux.txt
    - stubtest_allowlist_darwin.txt
    - stubtest_allowlist_win32.txt
  commands:
    - python -m mypy.stubtest psutil  --allowlist stubtest_allowlist.txt --allowlist stubtest_allowlist_linux.txt  # [linux]
    - python -m mypy.stubtest psutil  --allowlist stubtest_allowlist.txt --allowlist stubtest_allowlist_darwin.txt  # [osx]
    - python -m mypy.stubtest psutil  --allowlist stubtest_allowlist.txt --allowlist stubtest_allowlist_win32.txt  # [win32]
  requires:
    - mypy
    - psutil =={{ version.split(".")[:-1]|join(".") }}
    - python {{ python_min }}

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for psutil
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mr-c
