{% set name = "types-psutil" %}
{% set version = "5.9.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-psutil-{{ version }}.tar.gz
  sha256: bef91de096b77ff7bc3a92bafe466ee55f842286c1d734658b7c26b259078253

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3

test:
  files:  # [linux]
    - stubtest_allowlist.txt  # [linux]
  commands:  # [linux]
    - python -m mypy.stubtest --ignore-missing-stub psutil  --allowlist stubtest_allowlist.txt  # [linux]
  requires: [mypy]  # [linux]

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for psutil
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mr-c
