{% set name = "types-psutil" %}
{% set version = "5.9.5.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-psutil-{{ version }}.tar.gz
  sha256: 943a5f9556c1995097c89f50274330dd8d71d17bd73cbc6b09c61dbf4e114cc6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - setuptools
  host:
    - python >=3
    - setuptools
    - pip
  run:
    - python >=3

test:
  files:
    - stubtest_allowlist.txt
    - stubtest_allowlist_linux.txt
    - stubtest_allowlist_darwin.txt
    - stubtest_allowlist_win32.txt
  commands:
    - python -m mypy.stubtest psutil  --allowlist stubtest_allowlist.txt --allowlist stubtest_allowlist_linux.txt  # [linux]
    - python -m mypy.stubtest psutil  --allowlist stubtest_allowlist.txt --allowlist stubtest_allowlist_darwin.txt  # [osx]
    - python -m mypy.stubtest psutil  --allowlist stubtest_allowlist.txt --allowlist stubtest_allowlist_win32.txt  # [win32]
  requires:
    - mypy
    - psutil =={{ version.split(".")[:-1]|join(".") }}

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for psutil
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mr-c
